window.__ModuleLoader__.load({
  id: 'dsh-github-publisher',
  factory: (require) => {
    const module = { exports: {} }
    const exports = module.exports
    const source = {
      inject: ['slots'],
      apply(ctx) {
        const React = require('react')
        const { useState, useEffect } = React
        const ROUTE = '/_dsh/github-publisher'
        let openPanel = null
        const css = `.ghp-footer{border:0;background:transparent;color:var(--dsw-alias-label-secondary);cursor:pointer;border-radius:8px;padding:8px}.ghp-footer:hover{background:var(--dsw-alias-interactive-bg-hover)}.ghp-backdrop{pointer-events:auto;position:fixed;inset:0;background:#0008;display:flex;align-items:center;justify-content:center;z-index:9999}.ghp-panel{width:min(560px,calc(100vw - 32px));max-height:calc(100vh - 40px);overflow:auto;box-sizing:border-box;padding:20px;border-radius:16px;background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-primary);box-shadow:0 24px 80px #0007}.ghp-head{display:flex;justify-content:space-between;align-items:start;margin-bottom:16px}.ghp-head small{display:block;margin-top:4px;color:var(--dsw-alias-label-tertiary)}.ghp-head button{font-size:24px;border:0;background:none;color:inherit;cursor:pointer}.ghp-field{display:flex;flex-direction:column;gap:6px;margin:10px 0;font-size:13px}.ghp-field input,.ghp-field select,.ghp-field textarea{box-sizing:border-box;width:100%;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:var(--dsw-alias-bg-base);color:inherit;padding:9px}.ghp-field textarea{min-height:76px;resize:vertical}.ghp-row{display:grid;grid-template-columns:1fr 1fr;gap:12px}.ghp-preview{background:var(--dsw-specific-tip);border:1px solid var(--dsw-alias-border-l1);border-radius:10px;padding:12px;display:grid;gap:5px}.ghp-preview code{font-size:11px;word-break:break-all}.ghp-message{margin-top:10px;word-break:break-word}.ghp-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:18px}.ghp-actions button{border:1px solid var(--dsw-alias-border-l2);border-radius:8px;padding:9px 14px;background:transparent;color:inherit;cursor:pointer}.ghp-actions .primary{background:var(--dsw-alias-state-business-primary);color:white;border-color:transparent}.ghp-actions .danger{background:#c33}`
        ctx.effect(() => { const tag = document.createElement('style'); tag.textContent = css; tag.dataset.plugin = 'dsh-github-publisher'; document.head.appendChild(tag); return () => tag.remove() })
        async function call(payload) { const response = await fetch(ROUTE, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok || !data.ok) throw new Error(data.error || '请求失败'); return data }
        function Button(props) { return React.createElement('button', { className: 'ghp-footer', onClick: () => openPanel?.(true), title: '发布到 GitHub' }, props.wide ? '🚀 GitHub 发布' : '🚀') }
        function Panel() {
          const [open, setOpen] = useState(false), [account, setAccount] = useState(''), [projectPath, setProjectPath] = useState(''), [repository, setRepository] = useState(''), [visibility, setVisibility] = useState('public'), [tag, setTag] = useState('v0.1.0'), [title, setTitle] = useState(''), [notes, setNotes] = useState('Initial release.'), [preview, setPreview] = useState(null), [busy, setBusy] = useState(false), [message, setMessage] = useState('')
          useEffect(() => { openPanel = setOpen; return () => { openPanel = null } }, [])
          useEffect(() => { if (open) call({ action: 'status' }).then(x => { setAccount(x.account); setProjectPath(p => p || x.defaultProjectPath) }).catch(e => setMessage(e.message)) }, [open])
          if (!open) return null
          const reset = setter => e => { setter(e.target.value); setPreview(null) }
          const previewNow = async () => { setBusy(true); setMessage(''); try { setPreview(await call({ action: 'preview', projectPath, repository, visibility, tag, title, notes })) } catch (e) { setMessage(e.message) } finally { setBusy(false) } }
          const confirm = async () => { setBusy(true); setMessage(''); try { const x = await call({ action: 'confirm', token: preview.token, confirmation: preview.confirmation }); setMessage('发布成功：' + x.releaseUrl); setPreview(null) } catch (e) { setMessage(e.message) } finally { setBusy(false) } }
          const field = (label, node) => React.createElement('label', { className: 'ghp-field' }, React.createElement('span', null, label), node)
          return React.createElement('div', { className: 'ghp-backdrop', onMouseDown: e => e.target === e.currentTarget && setOpen(false) }, React.createElement('div', { className: 'ghp-panel' }, React.createElement('div', { className: 'ghp-head' }, React.createElement('div', null, React.createElement('b', null, '🚀 发布到 GitHub'), React.createElement('small', null, account ? '账号：' + account : '正在检查登录…')), React.createElement('button', { onClick: () => setOpen(false) }, '×')), field('项目目录', React.createElement('input', { value: projectPath, onChange: reset(setProjectPath) })), field('仓库名（留空自动取文件夹名）', React.createElement('input', { value: repository, onChange: reset(setRepository), placeholder: '自动' })), React.createElement('div', { className: 'ghp-row' }, field('可见性', React.createElement('select', { value: visibility, onChange: reset(setVisibility) }, React.createElement('option', { value: 'public' }, '公开'), React.createElement('option', { value: 'private' }, '私有'))), field('版本', React.createElement('input', { value: tag, onChange: reset(setTag) }))), field('Release 标题', React.createElement('input', { value: title, onChange: reset(setTitle), placeholder: tag })), field('发布说明', React.createElement('textarea', { value: notes, onChange: reset(setNotes) })), preview && React.createElement('div', { className: 'ghp-preview' }, React.createElement('b', null, '发布确认单'), React.createElement('div', null, '仓库：' + preview.plan.slug), React.createElement('div', null, '文件：' + preview.plan.fileCount + ' 个'), React.createElement('div', null, '可见性：' + preview.plan.visibility + '　版本：' + preview.plan.tag), React.createElement('code', null, preview.confirmation)), message && React.createElement('div', { className: 'ghp-message' }, message), React.createElement('div', { className: 'ghp-actions' }, React.createElement('button', { onClick: () => setOpen(false), disabled: busy }, '取消'), preview ? React.createElement('button', { className: 'primary danger', onClick: confirm, disabled: busy }, busy ? '发布中…' : '确认并发布') : React.createElement('button', { className: 'primary', onClick: previewNow, disabled: busy }, busy ? '检查中…' : '预检发布'))))
        }
        ctx.slots.inject('sidebar.footer.action', () => ctx.slots.register({ name: 'sidebar.footer.action', id: 'github-publisher', order: -50, label: 'GitHub 发布' }, Button))
        ctx.slots.inject('shell.overlay', () => ctx.slots.register({ name: 'shell.overlay', id: 'github-publisher' }, Panel))
      }
    }
    module.exports = source
    return module.exports
  }
})
